---

- name: COPY | Deploy private keys
  copy: >
    src={{ item }}
    dest={{ ssl_private_dir }}
    owner=root
    group=root
    mode=0600
  with_fileglob: "{{ ssl_local_private_dir }}/*.key"

- name: COPY | Deploy certificates
  copy: >
    src={{ item }}
    dest={{ ssl_certs_dir }}
    owner=root
    group=root
    mode=0644
  with_fileglob: "{{ ssl_local_certs_dir }}/*.crt"

- name: COPY | Deploy DH key
  copy: >
    src={{ item }}
    dest={{ ssl_dh_dir }}
    owner=root
    group=root
    mode=0644
  with_fileglob: "{{ ssl_local_dh_dir }}/*.pem"
