---

- name: INCLUDE | Prepare directories
  include: prepare.yml

- name: INCLUDE | Generate keys
  include: generate.yml

#- name: INCLUDE | Check all local keys
#  name: checks.yml

- name: INCLUDE | Deploy all files
  include: deploy.yml

